import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { getLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  return (
    <html lang={locale} data-bs-theme="dark">
      <body>
        <Providers>{children} </Providers>
      </body>
    </html>
  );
}
